### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by fried5** [spring-sprout/osoon#11]
![home copy 2](https://user-images.githubusercontent.com/16667816/30883625-b7c7c334-a347-11e7-82f1-8c973487e15c.png)

와이어프레임 던져봅니다
저는 이런 메인 구조를 상상했는데요, 일단 모임 리스트는 임의로 넣어봤구용
로그인하면 모임리스트 맨 위에 한 줄이 더 추가되서 참여이력과 비슷한 모임추천같은 게 뜨면 어떨까 싶네요
가입할 때 관심분야를 선택하면 모임 이력이 없어도 바로 추천할 수도 있을 것 같고요(막 던지기)

다시 보니.. 모임만들기는 캐러셀말고 메뉴 쪽에 놓는 게 접근하기 더 쉬울 것 같네요..ㅌㅌㅌ..하지만 저는 이만 자러..

**Comment by fried5** [comment]
뭔가 빠진 거나 수정할 것 피드백 부탁드려요~~

**Comment by whiteship** [comment]
우와오아!!

**Comment by KimJejun** [comment]
https://www.meetup.com/ko-KR/
예전에 봄싹 만들때 참고했던건데 
가입할때 관심분야량 주제들 선택하면 가입 후 페이지에 보이는 형식으로 되있네요.

**Comment by keesun** [comment]
좋네요. 상단에 `모임을 만들어 보세요`는 배너 형태로 돌아가면 좋겠네요. "모임 만들어 보세요", "모임에 참여해 보세요." 등등으로요.

모임 카드뷰 하단에 있는 게이지 바도 맘에 드네요.

그런데 우리 버튼 색 정말 검정색으로 하실껀가요? 느낌이 약간 상조.. 느낌...

**Comment by outsideris** [comment]
저건 와이어프레임이라 색없이 가서 그런걸로 보입니다. 검은색 버튼일수도 있지만. ㅎㅎ

**Comment by fried5** [comment]
와이어프레임이라서 그냥 흑백으로 했어요~~ ㅋㅋㅋㅋ
구조만 보시면 될 것 같습니다
다른 페이지도 짜서 공유드릴게욥

**Comment by outsideris** [comment]
혹시 생각하고 계신 디자인 공유 도구는 있으신가요? zeplin이나 invision 같은거요. 
최근에는 제플린만 써보긴 했는데 인비전도 좋아졌다면 상관없습니다. 이런 도구 쓰는게 가이드나 이런거 제작 안해도 되서 좋은거 같아서요.  무료로 쓰는 가격 정책을 정확히는 모르겠네요. 전에는 프로젝트 1개인가는 무료같았는데요.

**Comment by fried5** [comment]
네, 가이드는 제플린쓰면 될 것 같구요. 
프로토타이핑은 프로토파이가 손에 익긴한데 인비전이 웹으로 이것저것 공유되서 더 나을 것 같긴해요.
요거는 제가 인비전 좀 써보고 말씀드릴게요.
일단은 제플린만 하고 제 계정으로 초대드리면 될 것 같아요. 와쳐 수 상관없이 1개 플젝은 무료에요!(업로더는 1명으로 제한)

**Comment by outsideris** [comment]
프로토타이핑 도구는 필요없으시면 굳이 안쓰셔도 되긴합니다. 저는 디자인결과 공유의 의미로만 얘기했었어요.
(물론 쓰고 싶으시면 쓰셔도 되고요!)

**Comment by fried5** [comment]
대충 flow보는 용도로 하나 만들면 좋을 것 같긴 한데, 만들기 후달리면 안하겠습니다 ㅋㅋㅋ
