### ISSUE TITLE
모임 생성 API

### ISSUE THREAD

**Issue by KimJejun** [spring-sprout/osoon#13]
모임에 필요한 기능 코멘트 달아 주세요

요소
- 모임 제목, 상세 내용, 장소(전체 주소, 별칭), 시간, 신청기간(시작, 종료), 총 참가자수, 대표이미지 URL 를 받아야 함.

기능
- 참가 신청/취소
- 토픽(태그 추가)
- 모임 생성시 상태는 READY(준비) 상태, Publish(공개)로 변경해야 타인에게 노출되고 참여 가능
- 모임 참여시 참여자의 자동(선착순)/수동(관리자 승인) 참여 구분

**Comment by keesun** [comment]
https://github.com/spring-sprout/moilago/wiki/%EB%AA%A8%EC%9E%84-%EC%83%9D%EC%84%B1-%EA%B8%B0%EB%8A%A5-%EA%B8%B0%ED%9A%8D%EC%84%9C

기획서 참고해 주세요.

**Comment by keesun** [comment]
`GET /api/meeting/create`로 접속 시 다음의 데이터를 전달합니다.
- 현재 사용자가 최근에 사용했던 장소 정보 (locations[])
- 현재 사용자에 대한 정보 (name, imageUrl)
- 모임 태그 목록 (태그 자동 완성 지원)
- 미팅 온/오프 타입
- 온라인 타입

`POST /api/meeting/create`로 다음 데이터를 보내면 모임을 생성할 수 있습니다.
- 모임명 (필수)
- 온/오프라인 여부
- 장소 이름 (오프라인일 경우)
- 장소 주소 (오프라인일 경우)
- 슬랙/행아웃 중에 하나 선택 (온라인일 경우)
- 시작 일/시 (UTC)
- 종료 일/시 (UTC)
- 모임 이미지 URL
- 모임 설명
- 모임 태그
- Ready / Publish

응답으로는 생성된 모임 URL을 받을 수 있습니다. 혹은 에러 응답.

**Comment by keesun** [comment]
이슈가 너무 큰거 같아서 이 이슈는 모임 생성 API 만들기로 변경하고 참가 신청/취소는 다른 이슈로 만들께요.
