### ISSUE TITLE
모임 생성 UI

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#18]
수정해야할 사항
- [x] 모임 기간에 라디오 버튼 제거 및 끝나는 날짜 추가
- [x] '하루종일' 체크박스도 추가
- [x] 추천이미지 팝업 디자인
- [x] 시간 드롭다운 아이콘 필요할까 고민중
- [x] 카테고리 드롭다운으로 수정 및 상단으로 위치 변경
- [x] 사진 업로드 밑에 추천이미지 관련 기능 추가
- [ ] 추후 관리자용 뷰(출첵하는 내용) 필요함
- [ ] 맵 이미지 나중에 넣어야함

**Comment by fried5** [comment]
수정해야할 사항)
+모임 기간에 라디오 버튼 제거 및 끝나는 날짜 추가
+'하루종일' 체크박스도 추가
+시간 드롭다운 아이콘 필요할까 고민중
+카테고리 드롭다운으로 수정 및 상단으로 위치 변경
+사진 업로드 및에 추천이미지 관련 기능 추가
+추후 관리자용 뷰(출첵하는 내용) 필요함
+맵 이미지 나중에 넣어야함

**Comment by fried5** [comment]
![default](https://user-images.githubusercontent.com/16667816/35478069-a868291c-0416-11e8-9328-b4e2f7e08dc3.png)

**Comment by keesun** [comment]
- [ ]
