### ISSUE TITLE
docker-compose로 환경 구성

### ISSUE THREAD

**Issue by outsideris** [spring-sprout/osoon#19]

**Comment by outsideris** [comment]
@fried5 님은 [docker for mac](https://docs.docker.com/docker-for-mac/install/)을 설치해서 README 대로 실행하시면 됩니다.

**Comment by outsideris** [comment]
docker-compose에서 연결하느라고 https://github.com/spring-sprout/moilago/blob/master/src/main/resources/application.properties#L21 에서 neo4j의 주소를 수정했습니다. compose 안쓰고 로컬에서 직접 개발하실때 이부분 수정필요할텐데 참고해 주세요. @whiteship @KimJejun

**Comment by keesun** [comment]
@outsideris 저도 도커 쓰면서 개발할꺼라 나중에 readme에서 docker 안쓰고 개발하는 부분은 deprecation 시키죠. 감사합니다. 잘 됩니다.
