### ISSUE TITLE
SPA용 인증 API 개발하기

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#2]
https://spring.io/blog/2015/01/12/spring-and-angular-js-a-secure-single-page-application
https://spring.io/blog/2015/01/12/the-login-page-angular-js-and-spring-security-part-ii

**Comment by keesun** [comment]
https://geowarin.github.io/social-login-with-spring.html

**Comment by keesun** [comment]
@outsideris 조금 작업해 놨는데요.

일단 API는 GET /api/session 이 현재 로그인된 사용자 조회가 될거 같구요. 리턴으로 `{user : null}` 이 나가면 없는거고 있으면 이름이 담길꺼에요. 

로그인 하러가는 페이지는 페이스북으로 가게 될텐데 POST /signup/facebook 이라고 서버한테 보내면 서버가 페이스북에 보내줄꺼에요.

페이스북에서 로그인하고나면 / 루트로 올꺼구요. 그때다시 GET /api/session 조회하면 아마 이름이 들어있을 겁니다.

실제 구현된 코드는 facebook-login 이란 브랜치 보시거나 이 댓글 바로 위에 있는 글 한번 보시면 아마 이해되실꺼 같아요.

**Comment by outsideris** [comment]
과연 보면 이해가 될런지.... 프론트가 백엔드랑 디자인이 아직 둘다 없어서 작업진행이 약간 난항을 겪는 중.. ㅎㅎ 
facebook을 먼저 붙일거지?

**Comment by keesun** [comment]
네 일단은 페이스북 로그인만요. 백엔드에서 뭐가 필요한지 알려주세요.

**Comment by outsideris** [comment]
이슈에 만들어져 있는 모임 생성이랑 상세보기 API요.
