### ISSUE TITLE
로그인 UI

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#21]

**Comment by fried5** [comment]
![main copy 4](https://user-images.githubusercontent.com/16667816/31621739-728c3b2c-b2d5-11e7-900a-a81c1d516127.png)
로그인 UI 와이어프레임입니다.

**Comment by keesun** [comment]
위에 네모낳게 조그만 이미지말고 배경 전체에다가 이미지를 크게 까는건 어때요? 시원 시원하게..? 깔만한 이미지는 무료 이미지 사이트에서 group 이나 camping 등 맘에 드시는걸로 골라주시고요.

**Comment by fried5** [comment]
음. 메인이랑 결 맞춰서 일러스트 넣으려고 했는데, 말씀해주신 부분도 만들어볼게요~

**Comment by keesun** [comment]
아 이미 메인 배경이 있는거면 괜찮아요. 전 그냥 하얀 바탕인줄 알고요.
