### ISSUE TITLE
일시 정보를 어떻게 저장할 것이냐

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#27]
날짜나 시간은 입력하는 사람 입장에서 입력을 하겠죠? 가령 한국에 사는 사람은 한국 시간으로 언제부터 언제까지 할꺼나 혹은 언제부터 언제까지 모집할꺼다 등등.

같은 시간대에 사는 사람들이라면 별 문제가 없는데, 이 정보를 다른 시간대에 있는 사람들이 보면 햇갈릴 여지가 생기겠죠. 가령, 한국 시간 토요일 오전 11시면 시애틀에 사는 저는 금요일 저녁 7시에 해당하니까 아마도 그 모임을 놓치고 이미 모임이 다 끝난 시애틀 시간 토욜 오전 11시에 싱크업 하려고 하겠지만 그땐 이미 아무도 없겠죠.

시간 데이터를 어떻게 저장할 것이냐가 이 이슈의 주제입니다.

혼란을 없애려면 `입력값`과 `입력 하는 사람의 시간대` 그리고 `기준값 UTC` 그리고 `기준값을 보는 사람`을 고려해야 합니다. 

입력할 때는 입력값을 그대로 저장하지 않고 그 값을 기준값으로 변경하여 저장합니다.
보여줄 때도 마찬가지로 그 값을 그대로 보여주지 않고 보려는 사람의 시간대에 맞춰 보여줘야 합니다.

입력값은 있으니 입력하는 사람과 보려는 사람의 시간대 정보만 있으면 처리할 수 있을것 같은데... 그 정보를 어떻게 가져올 것이냐..

어떤 웹사이트들 들어가면 위치 정보 사용 허가 해줄꺼냐고 물어보는 웹 사이트들 보셨을텐데요. 우리도 그렇게 해야 하나? 싶었지만 그런 팝업이 뜨는거 자체가 유저한테 좀 귀찮기도 하고 사적인 정보를 요구하는거 같으니 안했으면 하거든요.

다른 대안으로는 일시 정보를 입력할 때 추가적으로 Timezone 정보를 입력 받는 방법이 있습니다. 물론 유저가 좀 귀찮겠죠? 또는 장소 정보에서 시간대 정보를 유추해내는 방법도 있지만 장소를 입력하지 않고
 시간만 입력한 경우엔 그럼 어떻게 할까요?

또는 HttpRequest의 헤더 정보에서 뽑아오는 방법도 있는데, 보통 `Accepted-Language` 정보는 자주 있어도 Timezon 정보는 별로 없어서 그 방법도 그리 완벽해 보이진 않습니다.

계속 고민해 보긴 할텐데 좋은 방법 있으시면 댓글로 의견 주세요.

**Comment by keesun** [comment]
아니면 그냥 보는 사람이 알아서 아.. 저건 한국에서 하는 모임이니까 당연히 한국 시간대 기준으로 썼겠지 내가 알아서 변환해야지 할 수도 있겠네요. 지금까지 그래왔던것처럼..

**Comment by miracle0k** [comment]
입력 받을때는 OS에 설정된 Timezone 기준으로 날짜가 찍힐테니 API 통신시 자바스크립트로 UTC로 변환한 후에 서버에 저장하고,  날짜 보여줄때는 API에서 UTC 기준으로 내려주고 자바스크립트에서 Timezone에 맞춰서 display해주면 되지 않을까요?

**Comment by outsideris** [comment]
브라우저 타암존으로 올려주면 서버에서 UTC로 변환 후 저장.
브라우저는 서버에서 UTC 받아서 브라우저 타임존에 맞게 보여주면 될것 같습니다.

```
new Date()
Thu Oct 19 2017 13:09:12 GMT+0900 (KST)
```

동의없어도 브라우저의 타임존을 알 수 있습니다.

**Comment by keesun** [comment]
네 서버 위치는 랜덤이라고 봐야해서 서버 시간에 의존하면 안될거 같아요. 브라우저에서 타임좀 가져오는게 좋겠네요. 그렇게 하는걸로!
