### ISSUE TITLE
DB 선정하기..

### ISSUE THREAD

**Issue by KimJejun** [spring-sprout/osoon#3]
뭘로 하죠? ㅋ

GraphDB 추천 합니다.
나름 잼있어요 촤하하

SDN 문서 : https://projects.spring.io/spring-data-neo4j/
다운로드 : https://neo4j.com/download/

Meeting 만들고 참여하면 아래 같은 형태로 만들어 집니다.
![graphsampe](https://user-images.githubusercontent.com/481114/30683384-38af6f7e-9ee8-11e7-9df8-a8f049a47a3a.PNG)

도커 compose 생성 필요

**Comment by keesun** [comment]
댓글... 우리가 만들지 말고 https://disqus.com/ 쓰는건 어떨까요?

**Comment by keesun** [comment]
서버 개발자 과반 이상(두명 중 한명)이 지지하는거니까 그래프 디비 쓰세요. 나도 딱히 반대하는 입장은 아니고, 대신 개발/배포할 때 편하게 그래프 디비 서버는 도커 compose 파일 하나 만들어 주세요.

**Comment by keesun** [comment]
그리고 모임 관련해서 설계 더 하고 싶으면, 모임에 참가 신청/취소, 실제 참석 여부, 사용자들 간의 following  기능까지 해보시고요. following 하는 사람들이 간다는 모임을 보여준다던가 할 수 있도록... 또는 following 하는 사람이 만든 모임도 보여줄 수 있고. 

모임에 토픽이라는 태그도 추가할 수 있게 해주고 역시나 사용자들은 관심있는 태그 팔로윙 할 수 있고 그것 관련 모임 뿌려줄 수 있으면 좋겠네요.

**Comment by KimJejun** [comment]
@keesun disqus 는 좀 느린감이 있어서.. 테스트 한번 해볼께요

**Comment by KimJejun** [comment]
도커는 저도 좀 봐야되서 보고 추가 할께요~
모임 관련 기능은 다른 이슈만들도록 할께요

**Comment by whiteship** [comment]
네 그려요
