### ISSUE TITLE
이름 정하기

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#4]

**Comment by fried5** [comment]
Fika [피카] 
스웨덴어, 반복되는 일상에서 벗어나 함께 모여 이야기를 나누고 휴식을 취한다

SAMAR [사마르] 
아랍어, 밤 늦도록 친구들과 즐거운 시간을 보내는 것

**Comment by keesun** [comment]
그대로는 도메인이 없어서 못쓸꺼 같고요. 조금 변형하면 쓸 수 있을지도 모르겠네요.

**Comment by keesun** [comment]
openfika.com 처럼 fika 앞에 뭘 좀 붙이면 쓸 수 있을거 같습니다.

**Comment by keesun** [comment]
사람들 연결 해 준단 의미로 pipe를 써도 좋을거 같습니다. 역시나 pipe.com은 만들 수가 없구요. openpipe.com 처럼 뭔가 앞에 붙여야 합니다.

**Comment by keesun** [comment]
glad2meetu.com 이것도 가능함.

**Comment by keesun** [comment]
bangawa.com 이것도

**Comment by keesun** [comment]
osoon.com 젤 짧고 맘에 드네요. 오순 도순에서 "오순"

**Comment by keesun** [comment]
@fried5 @outsideris @KimJejun 투표의 시간입니다. 각자 맘에 드는 도메인을 댓글로 달아 주세요. 여러개 남겨도 좋습니다. 기간은 이번주 금욜까지.

**Comment by keesun** [comment]
저는 osoon.io 랑 openfika.com 좋아요.

**Comment by outsideris** [comment]
osoon +1

**Comment by fried5** [comment]
osoon 귀엽네요~ 저도 여기 한표

**Comment by keesun** [comment]
그럼 과반을 넘었으니 제준님 의견과는 관계없이 osoon.io로 정하겠습니다.
