### ISSUE TITLE
모임 생성 POST의 데이터 형식.

### ISSUE THREAD

**Issue by outsideris** [spring-sprout/osoon#41]
`Meeting.java`를 보고 있는데 아직 제대로 요청 형태를 잘 몰라서 질문드립니다. 

* `MeetingOnOffType`같은 건 enum으로 정의되어 있는데 요청을 보낼때 데이터를 어떻게 보내야 하는건가요? `ONLINE, OFFLINE, BOTH`로 되어 있는데 문자열로 보내는건디 0,1,2로 보내는건지 잘 모르겠네요 
* `location`필드는 `MeetingLocation` 객체로 받게 되어 있는데 이건 어떻게 보내야하는건가요?  `{ location: { addr:'', name: '' }` 같은 식으로 중첩 JSON으로 보내면 되나요?

**Comment by keesun** [comment]
아직 작업이 덜 되서요. 요청 응답은 도메인 안쓰고 DTO 쓸꺼거든요 그래서 그거 보고 작업해 주시면 되는데 곧 작업해서 올린 담에 알려드릴께요.

**Comment by keesun** [comment]
일단 enum은 문자열로 보내시면 맵핑 됩니다. location은 중첩 JSON으로 보내시면 되구요. 아래는 샘플 요청 본문인데요. 모든 property 다 보내야 하는건 아니니까 그냥 참고만 하세요.

```
{
  "id": null,
  "title": "test meeting",
  "contents": "blah blah",
  "coverImage": null,
  "meetingOnOffType": "OFFLINE",
  "maxAttendees": 0,
  "location": {
    "id": null,
    "addr": "서울시 마포구 월드컵북로2길 65 5층",
    "name": "Toz",
    "latitude": 0.0,
    "longitude": 0.0,
    "user": null
  },
  "onlineType": null,
  "meetStartAt": null,
  "meetEndAt": null,
  "createdAt": null,
  "updatedAt": null,
  "meetingStatus": "READY",
  "admins": [
    
  ],
  "topics": [
    
  ],
  "autoConfirm": false
}
```

**Comment by keesun** [comment]
혹시 이슈 또 있으시면 열어주세요. 일단은 닫을께요.
