### ISSUE TITLE
모임 참가 신청시 제한 인원 확인

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#42]
## Description

제한 인원값이 0 보다 큰 경우에는 인원 체크한 다음에 신청 목록에 넣어주세요. 예외 처리도!

**Comment by KimJejun** [comment]
AttendMeetingRepository 에서 countByMeetingId 하면 자동 생성된 쿼리로 될 것 같은데 안되네요.
id(meeting) = {0} 이런 형식으로 생성되야 하는데 meeting.id = {} 이렇게 되서 못찾음.. 
슬프다 ㅠㅠ

**Comment by keesun** [comment]
ㅋㅋㅋㅋ아직 늦지 않았어요... JPA로 갈까요?

**Comment by KimJejun** [comment]
배우는 재미로 합니다... ㅋㅋㅋ

**Comment by keesun** [comment]
뭐 말리진 않겠습니다. ㅋㅋ

**Comment by KimJejun** [comment]
https://stackoverflow.com/questions/47132148/spring-data-neo4j-findby-relationentityid
왜 안되는 고양

**Comment by KimJejun** [comment]
https://jira.spring.io/browse/DATAGRAPH-1049
이슈로 올려 보라 해서 이슈로 올림.
