### ISSUE TITLE
DB 다시 생각해봅시다.

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#43]
## Description

Neo4j 재미있기는 한데.. 일단
1. Spring Data Neo4j에서 기본으로 제공하는 메서드도 제대로 작동하지 않음.
2. 고로, 거의 대부분의 메서드에 쿼리를 직접 짜게 됨.
3. 고로, 매우 개발 자체가 느리고, 깨지기 쉬운 코드를 작성 중.

JPA로 돌아가는 방법을 다시 생각해 보는게 좋을거 같습니다.

**Comment by KimJejun** [comment]
기본 기능 안되면 JPA 쓰는게 좋겠네요

**Comment by keesun** [comment]
```
	@Query("MATCH (m:Meeting)\n" +
            "OPTIONAL MATCH (m)-[r1:MEET_AT]-(l:MeetingLocation)\n" +
            "OPTIONAL MATCH (m)-[r2:IS_ABOUT]-(t:Topic)\n" +
            "OPTIONAL MATCH (m)-[r3:MANAGED_BY]-(u:User)\n" +
            "WHERE id(m) = {0} \n" +
            "RETURN *")
	Optional<Meeting> findById(long id);
```

findById가 안되서 이렇게 짜야 @_@... 돌아갑시다.

**Comment by keesun** [comment]
Neo4j 버전을 3.2 이상으로 올리니 해결 됐네요. 일단 계속 쓰는걸로.
