### ISSUE TITLE
API 문서화 필요

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#45]
## Description

문서화가 필요할 거 같네요. API 마다 입력값 예제랑 리턴값 예제가 있으면 프론트 개발할 때 조금은 더 편하시겠죠? Spring REST Doc이라는게 있던데 쓸만할지 모르겠네요. 옛날에 봤을 땐 애노테이션 떡칠이었는데.. (그거 말곤 딱히 대안이 없기도 하지만.. )

SRD를 쓸지 그냥 static한 문서 파일로 관리를 할지 고민해 보겠습니다.

**Comment by keesun** [comment]
SRD 보니까 테스트랑 연동 되어있군요. 애노테이션 떡칠은 다른 라이브러리랑 햇갈린거 같네요. 테스트에 붙는거면 한번 해볼만 할거 같네요.

**Comment by keesun** [comment]
API 테스트를 `MockMvc` 사용해서 작성하시고 `.andDo(document("update-cover-image"))` 이린거 할 줄 추가해 주시면 `docs/api/`  아래 문서가 쭉 생깁니다.

@KimJejun 되도록이면 mockMvc 사용해서 테스트 작성해 주시고요.
@outsideris 해당 위치에서 요청이나 응답 형식 확인하시면 됩니다. JSON 포매팅이 안되있어서 보기가 불편한데 그냥 포매팅 해주는 곳에다가 복붙해서 보시는게 좋을거 같네요.

**Comment by outsideris** [comment]
http://localhost:8080/docs/api/ 여기서 보는거 아닌가요? 아니면 이전에 뭐 실행해야 하나요?

**Comment by whiteship** [comment]
프로젝트 홈/docs/api

**Comment by outsideris** [comment]
아.. 그냥 아스키독으로 있는거군요.
