### ISSUE TITLE
나중을 위해서라도 모임 신청 기간 입력 가능해야 함

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#51]
## Description

모임 상태도 `모임 참가 신청 받는 중`이라는 상태가 필요할 듯.

**Comment by KimJejun** [comment]
MeetingStatus.REBLISHED 를 모임 참가 신청 중으로 사용하면 될 것 같네요.
모임 시작 상태는 필요 없을 것 같아서, 모집 종료(REGIST_CLOSED)로 변경 했습니다.

**Comment by keesun** [comment]
@KimJejun 이거 이미 처리한거 같으니까 이슈 닫을께요. 혹시 안된거 있으면 다시 여세요.
