### ISSUE TITLE
모임 수정 API 다듬기

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#60]
## Description

모임 수정 API는 두가지로 바꿀까 합니다. 부분 수정과 전체 수정인데요. 

부분 수정은 요청에 전달되는 입력값에 모임에 대한 모든 값이 들어있는게 아니라 일부 값들만 들어있다고 가정하고, 그 값들만 수정하는 겁니다. 이때는 `PUT` 을 쓸까 합니다.

반대로 전체 수정은 요청의 본문에 모임에 대한 모든 정보를 들고 있다고 가정합니다. 따라서 요청 본문에 있는 정보로 기존 모임의 모든 데이터를 수정합니다. 이때는 `POST`를 쓸까 합니다.

모임의 상태 정보나 일시 등을 변경할 때마다 서버에 반영하고 싶다면 `PUT`을 사용해서 해당 정보만 보내면 되고, 수정 폼에서 여러 정보를 변경한 뒤 `저장` 버튼을 클릭하여 반영시킬 때는 `POST`를 사용해서 해당 폼의 모든 정보를 같이 서버쪽에 보내야 합니다.

Usecase 1. 커버 이미지 변경

커버 이미지를 변경할 경우 또는 없는 상태에서 새로 이미지를 올리는 경우에, "우선 커버 이미지 올리기"라는 버튼을 클릭하여 이미지를 선택할겁니다. 그럼 서버로 POST /api/files 를 사용해서 해당 파일을 업로드하고 서버에서 응답으로 URL을 받습니다. 

1. 그럼 프론트에서 PUT 요청을 만들어서 /api/meeting/11 로 {"cover": "url"}을 보내주면, 해당 모임의 커버 이미지의 URL만 새로 URL로 변경합니다.

2. 또는 유저가 "저장" 버튼을 클릭하면 새로 받은 URL 정보와 함께 폼에 있는 모든 모임 정보를 서버쪽으로 POST /api/meeting/11 로 보내줍니다.

**Comment by outsideris** [comment]
그럼 POST로 수정하는 경우에는 필수 파라미터가 더 많은 건가요?

**Comment by whiteship** [comment]
필수 파라미터라기 보단 프론트에서 안넘겨준 값이 있으면 그 값은 없는 값으로 업데이트 할테니 폼에 있는 값 전부 다 넘겨주셔야 할 거
같아요.

**Comment by outsideris** [comment]
그럼 PUT만 있으면 되는거 아니에요? POST가 따로 있을대 어떤 부분이 좋은지 잘 모르겠어요.

**Comment by keesun** [comment]
화면단에서 유저가 수정하는 필드만 따로 모아서 보내주는게 편하시면 그렇게 하셔도 되고요. 그런거 신경 안쓰고 그냥 폼 전부 보내실꺼면 post쓰시면 되겠죠. 

쓰는쪽 마음이라 일단 둘 다 있으면 필요에 따라 쓰시지 않을까 싶었는데 put만 만들까요? 항상 수정하는 데이터만 온다고 가정하고?

**Comment by outsideris** [comment]
클라에서 특정 필드를 빠뜨리면 null로 업데이트 될테니 그게 신경쓰여서요. put으로 하면 업데이트할 필드만 신경쓰면 되는데 post로 보내려면 기존 필드는 기존 값으로 채워줘야 해서요. 이런 상황이면 전 지정한 필드만 없데이트되는 put만 있어도 될것 같아요.

**Comment by keesun** [comment]
그러시죠. 그럼 PUT 만 만들께요.
