### ISSUE TITLE
로그인 기능 추가

### ISSUE THREAD

**Issue by outsideris** [spring-sprout/osoon#7]
- 이메일, 비밀번호로 로그인한다.

**Comment by KimJejun** [comment]
로그인은 https 도 있고.. 비번 저장해 놓기도 좀 그래서, facebook, google, naver 정도로 third party 인증으로 하는게 어떨까요?

**Comment by whiteship** [comment]
좋치 페북이랑 구글만 일단 해볼까?

**Comment by outsideris** [comment]
화면도 소셜 로그인쪽으로 작업하겠습니다.

**Comment by outsideris** [comment]
@whiteship 구현된 로그인의 흐름을 모르겠습니다. ㅠ 일단 자바 서버 띄워서 로그인 버튼 눌러보면 다음과 같이 오류가 나고 있는데 어떤 앱으로 설정되어 있는지 모르겠습니다. Facebook 앱 ID를 환경변수로 설정해서 쓸 수 있어야 하지 않나 생각합니다.  

<img width="896" alt="2017-10-08 9 29 39" src="https://user-images.githubusercontent.com/390146/31316812-0604c610-ac70-11e7-9c55-55ae0f01fee5.png">

저게 안되어서 요청내용을 확인을 못하는데 제가 생각하는 흐름은....

1. 페이지에서 `/api/session`에 요청을 보내서 로그인 여부를 확인합니다. 
2. 로그인이 안되어 있으면 
    1. 페이스북 로그인 버튼을 보여줍니다.
    2. 사용자가 클릭하면 프론트엔드에서 페이스북과 연동해서 로그인 처리합니다.
    3. 페이스북에게 받은 로그인 정보를 `/signup/facebook`로 POST 요청을 보냅니다.
    4. 서버에서 로그인 처리를 합니다.

이렇게를 생각하고 있는데 현재 구현된 것과 흐름의 차이가 있는것처럼 느껴져서 정리가 필요해 보입니다. 코드는 아마 [여기](https://github.com/spring-sprout/moilago/commit/369ca4dd7224fe6a82beb3d47ccd47ddfe64a2e8#diff-2da9ec348c421cff272e6bc96328bd68R25)가 아닌가 싶은데 여기서 보내야하는 POST 요청의 데이터가 어떤 것인지 잘 모르겠습니다.(Spring 안본지가 너무 오래되어서 ㅠㅠ )


그리고 추가로 지금 Spring 애플리케이션에 뷰화면이 계속 업데이트 되고 있는데 제가 프론트화면 구성하고 있는데 서버쪽 뷰도 계속 업데이트할 예정인가요? SPA로 안갈 생각인지 어떤지도 논의해봐야할것 같습니다.

**Comment by keesun** [comment]
앱 설정은 제가 한번 봐볼께요. 저런 모드가 있는지도 몰랐네요.

흐름은.. 생각하신게 맞구요. 좀 더 자세히 설명 드리자면..
1. `GET /api/session` 으로 로그인 여부 체크
2. 없으면 `POST /signin/facebook` 요청 보내세요. 그럼 페이스북으로 연동해서 로그인 처리 됩니다.
3. 이때 해당 사용자가 우리 사이트에 한번도 로그인 하지 않은 사용자일 경우에 스프링 소셜이 내부적으로 가입 URL인 `/signup/`으로 요청을 보냅니다.
4. 제가 구현한 그 컨트롤러에서 가입 `/signup/`은 별도의 처리 없이 바로 로그인 하도록 구현했습니다. 

그래서, 로그인 하려면 프론트에서 해주실 작업은 1번하고 2번 밖에 없어요. 3,4는 스프링 소셜이 알아서 해주는거라.. 저희가 요청을 직접 만들지 않아요.

SPA로 가는거에요. 제가 뷰 만들어 놓은건 서버 기능 테스트 용이지 배포용은 아닙니다. 나중에 서버에서 처리해야하는 URL 몇개 빼고는 전부 SPA 앱이 만든 페이지로 보내게 할꺼에요. 아마 다음번 마일스톤부턴 그렇게 하지 않을까 싶네요. 지금 당장은 로그인 기능 확인하려고 간단하게 뷰 만들어 본것일 뿐이에요.

**Comment by keesun** [comment]
![2017-10-08 12 17 45](https://user-images.githubusercontent.com/463657/31320035-b5848f42-ac22-11e7-9862-a72299a6566d.png)

이런 설정이 있었군요. 공개 모드로 바꿨으니까 이젠 아마 될꺼에요.

**Comment by outsideris** [comment]
이제 곧 잘거지만.. 저 흐름에서 2번을 제대로 이해못했습니다. 
페이스북 로그인 여부는 브라우저가 알고 있는 거라서 페북 로그인 버튼을 붙이면 브라우저에서 로그인 여부를 재 확인한 뒤에 해당 사이트에 정보를 줄건지 확인하고 이를 서버에 보내게 되는데 저 2번 과정에서 `/signin/facebook`에 요청을 보낼때는 어떤 정보를 보내나요? 설명으로 보면 요청을 보내명 서버에서 로그인 처리를 하는것처럼  나와있는데 제가 이해한 것은 프론트앤드가 페북 로그인 처리를 하고 서버에 보내면 서버는 우리 사이트의 로그인 처리(이 과정에서 페북에 재확인할 수도 있지만.)하는 것이라서요. 

저 요청을 보낼때 어떤 정보를 보내야 하는지 아니면 이제 스프링소셜을 쓴거면 관련 문서등을 링크주면 좋을거 같습니다.

**Comment by whiteship** [comment]
/signin/facebook 이 전부에요 다른 정보 보낼꺼 없어요. 그냥 Post 로 저 요청을 우리 서버로 보내주면 그게 끝이에요.

관련 문서는 제 이슈에 링크 걸어 뒀는데요 거기에 Client 부분 보시면 도움이 될거 같습니다.

**Comment by keesun** [comment]
@outsideris 제가 착각했네요.

    <form className="form-inline" action="/signin/facebook" method="post">
        <input type="hidden" name="scope" value="public_profile, email" />
        <button className="btn btn-outline-success" type="Submit">로그인</button>
    </form>

email 정보가 안오길래 왜그러나 봤더니 scope을 넘겨줘야 가져오네요. 일단 public_profile이랑 email 만 가져오게 scope 정보를 보내주셔야 할거 같습니다.

**Comment by outsideris** [comment]
OK!
