### ISSUE TITLE
모임 생성 페이지 

### ISSUE THREAD

**Issue by outsideris** [spring-sprout/osoon#8]
- 회원은 누구나 만들 수 있다.
  - 현재는 무료 모임만
  - 모임 제목, 상세 내용, 장소, 시간, 신청기간, 총 참가자수, 대표이미지를 받아야 함.
  - WYSIWYG 에디터 필요할듯(사진 업로드도 필요하다)
  - 장소를 지도에 표시해야 하므로 지도로 좌표나 장소 정보로 받아야함.(네이버 지도?)
  - 카테고리 필요한가?

**Comment by KimJejun** [comment]
api/meeting/make 로 만들었습니다.
지금은 제목, 상세 내용만 받게 만들었는데요. Meeting 클래스 참조 하셔서 파라미터로 넘겨주시면 제가 api 수정해서 저장 되게 변경할께요.

userId 파라미터 부분은 아직 로그인하고 연동이 안된 부분이 있어서 나중에 처리할 예정이라.. 
임의로 회원하나 생성해서 넣어 주시면 됩니다. 

api 테스트 하실때, SecurityConfiguration 클래스에 아래 부분 주석 처리 해서 변경 하시면 인증 없이 할수 있어요
```
 //.antMatchers("/api/**").authenticated()
 .antMatchers("/api/**").permitAll()
```

**Comment by KimJejun** [comment]
인증 기반으로 처리되도록 수정했습니다.
로그인 후 하시면 되요!

**Comment by outsideris** [comment]
아 이거 `api/meeting/create`로 바뀌었군요.

**Comment by keesun** [comment]
네 아마도 제가 바꾼거 같구요. `GET /api/meeting/create` 쓰시면 생성 화면에 필요한 데이터를 받을 수 있고요 (기존에 썼던 장소, 현재 사용자 정보, 토픽 목록), `POST /api/meeting/create` 쓰시면 모임 생성할 수 있게 만드는 중입니다.

**Comment by outsideris** [comment]
요거는 그냥 적어둔거고 코드 보고 금새 찾았습니다. neo4j 오류만 해결되면 금새 요청해 볼 수 있을것 같아요. 일단 막상 form 요소가 많아서 화면 구성을 고민중인데 일단 기능위주로 만들고 디자인맞춰서 재수정해야 할 것 같아요.  전 그동안 화면단 계속 좀 작업하고 있을게요 
모임생성 완료되면 한번 얘기해 주세요.

**Comment by keesun** [comment]
네 지난주까진 커버 이미지 업로드 작업하느라 이쪽 손을 못댔네요. 이번주는 모임 개설 API 다듬을테니 쓸만해지면 말씀 드릴께요.

**Comment by outsideris** [comment]
API를 이용한 기본 생성 기능은 완료했으므로 여기서 닫고 세부 이슈로 다시 만들겠습니다.
