### ISSUE TITLE
모임 상세 보기 페이지

### ISSUE THREAD

**Issue by outsideris** [spring-sprout/osoon#9]
모임 상세 보기
  - 모임을 클릭하면 모임의 상세 내용을 볼 수 있다.
  - 모임의 상세 내용과 지도 등이 표시되어야 함.(현재 참가 현환도)
  - 참가자 목록 등은 추가 참가신청 기능에서 만든다. 버튼등의 위치는 필요하다. 일단 페이지 개발만..

**Comment by KimJejun** [comment]
/api/meeting/show 로 id(Meeting) 파라미터 넘겨 주시면 됩니다

**Comment by outsideris** [comment]
API를 이용한 기본 생성 기능은 완료했으므로 여기서 닫고 세부 이슈로 다시 만들겠습니다.
